spring:
  application:
    name: recommendation-service
  main:
    allow-bean-definition-overriding: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_absent
    visibility.field: any
    visibility.getter: none
    visibility.setter: none
    visibility.is-getter: none
  security:
    user:
      name: user
      password: pass
  sleuth:
    enabled: false
    sampler:
      probability: 0
    web:
      additionalSkipPattern: ^/actuator.*
  zipkin:
    enabled: false
    service:
      name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health,info,heapdump,prometheus,threaddump,mappings,env,conditions,configprops,loggers,features
  endpoint:
    loggers:
      enabled: true
    info:
      cache:
        time-to-live: 5s
    prometheus:
      enabled: true
      cache:
        time-to-live: 5s
    health:
      show-details: always
      cache:
        time-to-live: 5s
  metrics:
    distribution:
      percentiles:
        all: 0.5, 0.95, 0.99, 0.999
      slo:
        "http.server.requests": 100ms, 200ms, 400ms
    export:
      prometheus:
        enabled: true
        descriptions: false
        step: 1m

springdoc:
  swagger-ui:
    path: /api-docs

info:
  app:
    name: ${spring.application.name}
    version: @project.version@
  build:
    date: @maven.build.timestamp@
  java:
    vm:
      vendor: ${java.vm.vendor}
      name: ${java.vm.name}
      version: ${java.vm.version}
